# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSystem_app', '0004_system_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
