# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSystem_app', '0005_auto_20161031_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
